-- Compatibility: ensure users table has the columns expected by current auth/runtime queries.
ALTER TABLE users
ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'user',
ADD COLUMN IF NOT EXISTS balance DECIMAL(20,8) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS concurrency INT NOT NULL DEFAULT 5,
ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active',
ADD COLUMN IF NOT EXISTS username VARCHAR(100) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS totp_secret_encrypted TEXT,
ADD COLUMN IF NOT EXISTS totp_enabled BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS totp_enabled_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS signup_source VARCHAR(20) NOT NULL DEFAULT 'email',
ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS balance_notify_enabled BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS balance_notify_threshold_type VARCHAR(20) NOT NULL DEFAULT 'fixed',
ADD COLUMN IF NOT EXISTS balance_notify_threshold DECIMAL(20,8),
ADD COLUMN IF NOT EXISTS balance_notify_extra_emails TEXT NOT NULL DEFAULT '[]',
ADD COLUMN IF NOT EXISTS total_recharged DECIMAL(20,8) NOT NULL DEFAULT 0;
